version: '3'
services: 
  postgres:
    image: postgres:latest
    container_name: postgres
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: graphscript
    volumes:
      - './data:/data/db'
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
  api:
    build: .
    container_name: graphscript
    command: npm run dev
    ports: 
      - '3333:3333'
    volumes: 
      - .:/app
    depends_on: 
      - postgres
      - redis
    links:
      - postgres
      - redis

