export default {
  AUTH_INVALID_TOKEN: 'Token is invalid',

  AUTH_NOT_FOUND: 'Authorization Header not found',
  JOB_IMPORT_ORDER: 'JOB_IMPORT_ORDER',
  JOB_NOT_FOUND: (name: string): string =>
    `JOB ${name.toUpperCase()} NOT FOUND`,
  JOB_PURGE: 'JOB_PURGE',

  JOB_RECOVERY_MAILER: 'JOB_RECOVERY_MAILER',
  JOB_REGISTRATION_MAILER: 'JOB_REGISTRATION_MAILER',
  JOB_SERVICE_COMPLETE: 'JOB_SERVICE_COMPLETE',
  JOB_SERVICE_CREATED: 'JOB_SERVICE_CREATED',
  JOB_SERVICE_DISCARDED: 'JOB_SERVICE_DISCARDED',
  JOB_SERVICE_EXECUTION: 'JOB_SERVICE_EXECUTION',
  JOB_SERVICE_POOLING: 'JOB_SERVICE_POOLING',
  JOB_SERVICE_WAITING_WINDOW: 'JOB_SERVICE_WAITING_WINDOW',

  PRIORITY_CRITICAL: 1,
  PRIORITY_HIGH: 2,
  PRIORITY_LOW: 3,

  USER_NOT_FOUND: 'User not found',
  USER_PASSWORD_INVALID: 'Password is wrong, try again',
};
